# Generated by Django 4.1.3 on 2022-11-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_item_price_item_cold_price_item_hot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
