# Generated by Django 4.1.3 on 2022-11-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_collection_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='mobile_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='mobile_number',
            field=models.CharField(max_length=11),
        ),
    ]
