# Generated by Django 4.1.3 on 2022-11-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_caffeinatedadd_item_caffeinated_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='caffeinated_add',
        ),
        migrations.AddField(
            model_name='item',
            name='espresso_shot',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='item',
            name='milk',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='item',
            name='syrup_pump',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='item',
            name='whip_cream',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.DeleteModel(
            name='CaffeinatedAdd',
        ),
    ]
