# Generated by Django 4.1.3 on 2022-11-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_item_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bottled_water',
            field=models.BooleanField(default=False),
        ),
    ]
