# Generated by Django 4.1.3 on 2022-11-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderitem_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='hot_cold',
            field=models.CharField(blank=True, default='hot', max_length=4, null=True),
        ),
    ]
