# Generated by Django 4.1.3 on 2022-11-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_item_bottled_water'),
    ]

    operations = [
        migrations.CreateModel(
            name='OthersAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_rice', models.PositiveSmallIntegerField(blank=True, default=20, null=True)),
                ('rice_platter', models.PositiveSmallIntegerField(blank=True, default=30, null=True)),
                ('aligue_platter', models.PositiveSmallIntegerField(blank=True, default=20, null=True)),
                ('espresso_shot', models.PositiveSmallIntegerField(blank=True, default=40, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='bottled_water',
        ),
        migrations.RemoveField(
            model_name='item',
            name='espresso_shot',
        ),
        migrations.RemoveField(
            model_name='item',
            name='milk',
        ),
        migrations.RemoveField(
            model_name='item',
            name='syrup_pump',
        ),
        migrations.RemoveField(
            model_name='item',
            name='whip_cream',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bottled_water',
            field=models.BooleanField(default=False),
        ),
    ]
