# Generated by Django 4.1.3 on 2022-11-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_othersadd_remove_item_bottled_water_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='bottled_water',
        ),
    ]
