# Generated by Django 4.1.3 on 2022-11-10 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderitem_hot_cold'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaffeinatedAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk', models.PositiveSmallIntegerField(default=20)),
                ('whip_cream', models.PositiveSmallIntegerField(default=30)),
                ('syrup_pump', models.PositiveSmallIntegerField(default=20)),
                ('espresso_shot', models.PositiveSmallIntegerField(default=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='espresso_shot',
        ),
        migrations.RemoveField(
            model_name='item',
            name='milk',
        ),
        migrations.RemoveField(
            model_name='item',
            name='syrup_pump',
        ),
        migrations.RemoveField(
            model_name='item',
            name='whip_cream',
        ),
        migrations.AddField(
            model_name='item',
            name='caffeinated_add',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.caffeinatedadd'),
        ),
    ]
