# Generated by Django 4.1.3 on 2022-11-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_caffeinatedadd_remove_item_espresso_shot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caffeinatedadd',
            name='espresso_shot',
            field=models.PositiveSmallIntegerField(blank=True, default=40, null=True),
        ),
        migrations.AlterField(
            model_name='caffeinatedadd',
            name='milk',
            field=models.PositiveSmallIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='caffeinatedadd',
            name='syrup_pump',
            field=models.PositiveSmallIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='caffeinatedadd',
            name='whip_cream',
            field=models.PositiveSmallIntegerField(blank=True, default=30, null=True),
        ),
    ]
