# Generated by Django 4.1.3 on 2022-11-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_item_others_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bottled_water',
            field=models.BooleanField(default=False),
        ),
    ]
