# Generated by Django 4.1.3 on 2022-11-10 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_caffeinatedadd_espresso_shot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='caffeinated_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.caffeinatedadd'),
        ),
    ]
