# Generated by Django 4.1.3 on 2022-11-27 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderitem_bottled_water'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='others_add',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='others_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.othersadd'),
        ),
    ]
