# Generated by Django 4.1.3 on 2022-11-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_item_caffeinated_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='espresso_shot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='milk',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='syrup_pump',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='whip_cream',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
