# Generated by Django 4.1.3 on 2022-11-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orderitem_espresso_shot_orderitem_milk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='espresso_shot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='milk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='syrup_pump',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='whip_cream',
            field=models.BooleanField(default=False),
        ),
    ]
