# Generated by Django 4.1.3 on 2022-11-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_item_espresso_shot_item_milk_item_syrup_pump_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hot_cold',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold')], default='HOT', max_length=5),
        ),
    ]
