# Generated by Django 4.1.3 on 2022-11-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_item_caffeinated_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othersadd',
            name='espresso_shot',
        ),
        migrations.AddField(
            model_name='othersadd',
            name='bottled_water',
            field=models.PositiveSmallIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='othersadd',
            name='aligue_platter',
            field=models.PositiveSmallIntegerField(blank=True, default=120, null=True),
        ),
        migrations.AlterField(
            model_name='othersadd',
            name='rice_platter',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True),
        ),
    ]
