# Generated by Django 4.1.3 on 2022-11-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_othersadd_espresso_shot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='aligue_platter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plain_rice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rice_platter',
            field=models.BooleanField(default=False),
        ),
    ]
