# Generated by Django 4.1.3 on 2022-11-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_orderitem_aligue_platter_orderitem_plain_rice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzadAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacon', models.PositiveSmallIntegerField(blank=True, default=30, null=True)),
                ('pepperoni', models.PositiveSmallIntegerField(blank=True, default=40, null=True)),
                ('ham', models.PositiveSmallIntegerField(blank=True, default=30, null=True)),
                ('cheese', models.PositiveSmallIntegerField(blank=True, default=30, null=True)),
            ],
        ),
    ]
