# Generated by Django 4.1.3 on 2022-11-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_pizzadadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzadadd',
            name='cheese',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
    ]
