# Generated by Django 4.1.3 on 2022-11-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_item_hot_cold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hot_cold',
        ),
    ]
