# Generated by Django 4.1.3 on 2022-11-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_orderitem_bacon_orderitem_cheese_orderitem_ham_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzadAdd',
            new_name='PizzaAdd',
        ),
    ]
