# Generated by Django 4.1.3 on 2022-11-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_item_hot_cold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hot_cold',
            field=models.CharField(default='hot', max_length=4),
        ),
    ]
