# Generated by Django 4.1.3 on 2022-11-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_item_hot_cold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hot_cold',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold')], default='Hot', max_length=5),
        ),
    ]
