# Generated by Django 4.1.3 on 2022-11-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_pizzadadd_pizzaadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_rice', models.PositiveSmallIntegerField(blank=True, default=30, null=True)),
                ('rice_platter', models.PositiveSmallIntegerField(blank=True, default=100, null=True)),
                ('aligue_platter', models.PositiveSmallIntegerField(blank=True, default=120, null=True)),
                ('bottled_water', models.PositiveSmallIntegerField(blank=True, default=20, null=True)),
            ],
        ),
    ]
