# Generated by Django 4.1.3 on 2022-11-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_item_hot_cold_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold')], max_length=5),
        ),
    ]
