# Generated by Django 4.1.3 on 2022-11-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_mainadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk', models.PositiveSmallIntegerField(blank=True, default=20, null=True)),
                ('whip_cream', models.PositiveSmallIntegerField(blank=True, default=30, null=True)),
                ('syrup_pump', models.PositiveSmallIntegerField(blank=True, default=20, null=True)),
                ('espresso_shot', models.PositiveSmallIntegerField(blank=True, default=40, null=True)),
                ('bacon', models.PositiveSmallIntegerField(blank=True, default=30, null=True)),
                ('pepperoni', models.PositiveSmallIntegerField(blank=True, default=40, null=True)),
                ('ham', models.PositiveSmallIntegerField(blank=True, default=30, null=True)),
                ('cheese', models.PositiveSmallIntegerField(blank=True, default=50, null=True)),
                ('plain_rice', models.PositiveSmallIntegerField(blank=True, default=30, null=True)),
                ('rice_platter', models.PositiveSmallIntegerField(blank=True, default=100, null=True)),
                ('aligue_platter', models.PositiveSmallIntegerField(blank=True, default=120, null=True)),
                ('bottled_water', models.PositiveSmallIntegerField(blank=True, default=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CaffeinatedAdd',
        ),
        migrations.DeleteModel(
            name='MainAdd',
        ),
        migrations.DeleteModel(
            name='OthersAdd',
        ),
        migrations.DeleteModel(
            name='PizzaAdd',
        ),
    ]
