# Generated by Django 4.1.3 on 2022-11-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_rename_price_item_hot_cold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Coffee Classics', 'Coffee Classics'), ('Special Latte', 'Special Latte'), ('Frappe', 'Frappe'), ('Other Drinks', 'Other Drinks'), ('Starters', 'Starters'), ('Silog Meals', 'Silog Meals'), ('Burger with Fries', 'Burger with Fries'), ('All About Wings', 'All About Wings'), ('Pasta', 'Pasta'), ('Pizza', 'Pizza'), ('Main Course', 'Main Course'), ('Sizzlers', 'Sizzlers')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cold_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='espresso_shot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='hot_cold',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Cold', 'Cold')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='hot_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='constant/cafe.jpg', null=True, upload_to='items-img'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='milk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='syrup_pump',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='whip_cream',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
