# Generated by Django 4.1.3 on 2022-12-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_deliveryfee_arevalo_deliveryfee_city_proper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='maximum_delivery_fee',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
