# Generated by Django 4.1.3 on 2022-11-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
