# Generated by Django 4.1.3 on 2022-11-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_item_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='users',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='espresso_shot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='milk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='syrup_pump',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='whip_cream',
            field=models.BooleanField(default=False),
        ),
    ]
