# Generated by Django 4.1.3 on 2022-11-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_item_users_alter_orderitem_espresso_shot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='hot_or_cold',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold')], default='Hot', max_length=5),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hot_cold',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
