# Generated by Django 4.1.3 on 2022-12-22 08:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0030_alter_deliveryfee_lapuz'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_or_cold', models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold')], default='Hot', max_length=5)),
                ('milk', models.BooleanField(default=False)),
                ('whip_cream', models.BooleanField(default=False)),
                ('syrup_pump', models.BooleanField(default=False)),
                ('espresso_shot', models.BooleanField(default=False)),
                ('bacon', models.BooleanField(default=False)),
                ('pepperoni', models.BooleanField(default=False)),
                ('ham', models.BooleanField(default=False)),
                ('cheese', models.BooleanField(default=False)),
                ('plain_rice', models.BooleanField(default=False)),
                ('rice_platter', models.BooleanField(default=False)),
                ('aligue_platter', models.BooleanField(default=False)),
                ('bottled_water', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('hot_cold', models.CharField(default='', max_length=4)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('ordered', models.BooleanField(default=False)),
                ('in_cart', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
