# Generated by Django 4.1.3 on 2022-11-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_orderitem_hot_or_cold_alter_orderitem_hot_cold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
