# Generated by Django 4.1.3 on 2022-12-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_favoriteitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitem',
            name='hot_cold',
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='in_cart',
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='total_price',
        ),
    ]
