# Generated by Django 4.1.3 on 2022-12-22 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_favoriteitem_hot_cold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
