# Generated by Django 4.1.3 on 2022-12-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_favoriteitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitem',
            name='quantity',
        ),
    ]
