# Generated by Django 4.1.3 on 2022-11-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_item_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='in_cart',
        ),
    ]
