# Generated by Django 4.1.3 on 2022-11-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_item_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
