# Generated by Django 4.1.3 on 2022-11-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='customer',
        ),
    ]
